name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * 1"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: 
    branches: [ master ]
    paths-ignore:
      - README.md
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          commits_authoring: xjy46566696@gmail.com, me@luomingxu.cn
          # followup
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: user
          plugin_followup_archived: no
          # starlist
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: star_list
          # habits 有问题
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Asia/Shanghai
